In [ ]:
# metodo de tratar tabelas

In [1]:
import os
import get_file_word as gf
import datetime
import pandas as pd

#setar variáveis onde estão arquivos
fileExt = r".docx"
fileExt2 = r".doc"

fileDir_semNF = r"/Users/wpessoa/repositorios/NGE/words_semNota/"

# verificar se existe o diretório
print("Existe esse diretório? ",os.path.exists(fileDir_semNF)) 
files_array_semNF = [_ for _ in os.listdir(fileDir_semNF) if _.endswith(fileExt)]
print("Quantidade de arquivos do word no diretório: ",len(files_array_semNF)) # ARQUIVOS DOCX

# rodar método get_info para ler aquivos do Word e retornar features de cada arquivo
# argumentos (diretório e array dos arquivos word)
# retorna (NºID,Qtd_caracteres,Qtd_tabela,Qtd_image,data)

var_semNF=gf.get_info(fileDir_semNF,files_array_semNF)

Existe esse diretório?  True
Quantidade de arquivos do word no diretório:  22
ID235880-AgendaPara_MÇxico_2020_Normalizada (1).docx
ID235980-Educação Infantil  4 e 5  anos - Diagramar.docx
ID235985-EF ANOS FINAIS CONSOLIDADO.docx
ID235983-EJA - ANOS INICIAIS_Diagramar.docx
ID235905-EstudoRegimeEspecialServicos_NormalizacaoCompleta_20200831.docx
ID235909-CAMEX_Estudo1_consolidadoAI_normalizado.docx
ID235876-2020-05-25 AgendaPara_Alemanha_2020_Normalizada TRAD _rev.docx
ID235798-2020-08-20 MINERACAO NO BRASIL RUMO A UMA INDUSTRIA PRODUTIVA_ SEGURA E SUSTENTA´VEL (1).docx
ID235986-EF ANOS INICIAIS CONSOLIDADO.docx
ID235874-2020-08-17 20200724_MC_GUIA FINANCIAMENTO_CLIMA_Aprovada_V01_NORMALIZADO.docx
ID235984-EJA - ENSINO MÉDIO - Diagramar.docx
ID235806-20200721_MC_MDS Comp Ind_v01_Aprovada_Normalizado (1).docx
ID235882-AgendaPara_CoreiadoSul_Normalizada (1).docx
ID235881-AgendaPara_ReinoUnido_Normalizada (1).docx
ID235964-VF MINUTA DE PUBLICAÇÃO sobre teletrabalho em países selecionados vf rev setembro 04.docx
ID235878-20200817_Água_de_reúso_Normalizado.docx
ID235981-EJA - ANOS FINAIS - Diagramar.docx
ID235883-AgendaPara_Franáa_Normalizada (1).docx
ID236021-2020-06-02 AgendaPara_Japao_2020_Normalizada.docx
ID235979-Educação Infantil  3 anos - Diagramar.docx
ID235832-2020-08-07 Difusão da I4.0 - Versão para publicação_revisao2.docx
ID236025-2020-09-16 Concorrência Justa e Defesa Comercial na crise_versão final (1).docx

In [54]:
# converter veriável de retorno do método para Dataframe
df = pd.DataFrame(var_semNF,columns=['Nº DA PLANILHA',"Qtd_PG_word","Qtd_carac","Qtd_tabela","Qtd_image","Qtd_estilos", "Data"])
df.head()

,Nº DA PLANILHA,Qtd_PG_word,Qtd_carac,Qtd_tabela,Qtd_image,Qtd_estilos,Data
0,235880,26,17783,3,2,23,2020-08-26
1,235980,11,163469,12,65,15,2020-09-14
2,235985,424,660609,107,75,27,2020-09-16
3,235983,30,66895,128,77,43,2020-11-09
4,235905,75,97635,147,96,54,2020-08-31

In [55]:
df

,Nº DA PLANILHA,Qtd_PG_word,Qtd_carac,Qtd_tabela,Qtd_image,Qtd_estilos,Data
0,235880,26,17783,3,2,23,2020-08-26
1,235980,11,163469,12,65,15,2020-09-14
2,235985,424,660609,107,75,27,2020-09-16
3,235983,30,66895,128,77,43,2020-11-09
4,235905,75,97635,147,96,54,2020-08-31
5,235909,38,75538,152,100,21,2020-09-02
6,235876,30,23238,154,109,29,2020-08-21
7,235798,142,247205,175,132,26,2020-08-20
8,235986,374,586948,277,140,21,2020-09-16
9,235874,44,69155,296,148,27,2020-11-09
10,235984,30,78414,315,150,42,2020-11-09
11,235806,64,82304,317,157,25,2020-11-09
12,235882,20,12344,319,159,25,2020-08-26
13,235881,23,14560,321,161,28,2020-08-26
14,235964,48,72824,323,163,16,2020-09-04
15,235878,67,87223,336,175,127,2020-08-17
16,235981,28,65594,359,177,42,2020-11-09
17,235883,22,14344,361,179,29,2020-08-26
18,236021,29,22781,363,181,20,2020-09-19
19,235979,45,72613,370,228,15,2020-09-14
20,235832,34,70983,372,232,16,2020-08-07
21,236025,24,33141,377,237,19,2020-09-16

In [56]:
# verificando tipo das variáveis
df.dtypes

Nº DA PLANILHA    object
Qtd_PG_word       object
Qtd_carac          int64
Qtd_tabela         int64
Qtd_image          int64
Qtd_estilos        int64
Data              object
dtype: object

In [57]:
# converter tipo para inteiros e data
df["Nº DA PLANILHA"] = pd.to_numeric(df["Nº DA PLANILHA"], errors='coerce')
df["Data"] = pd.to_datetime(df["Data"])

In [58]:
df.dtypes

Nº DA PLANILHA             int64
Qtd_PG_word               object
Qtd_carac                  int64
Qtd_tabela                 int64
Qtd_image                  int64
Qtd_estilos                int64
Data              datetime64[ns]
dtype: object

In [59]:
#Convertendo arquivo excel em dataframe

excelDir ="/Users/wpessoa/repositorios/Fluxo_Editorial/dados/"
excelFile_semNF = pd.read_excel(excelDir+'Exercicio_estimativa_de_paginas_2019_2020.xlsx',"SEM_NOTA_FISCAL")

In [60]:
len(excelFile_semNF.columns)

26

In [61]:
# selecionando apenas colunas necessárias
colunas=['ENTIDADE','PUBLICAÇÃO','Nº de páginas WORD','Nº de páginas estimado', 'COMPLEXIDADE','FORNECEDOR','Nº DA PLANILHA','STATUS DE PGTO']
excelFile2 = excelFile_semNF[colunas]

In [62]:
excelFile2.columns

Index(['ENTIDADE', 'PUBLICAÇÃO', 'Nº de páginas WORD',
       'Nº de páginas estimado', 'COMPLEXIDADE', 'FORNECEDOR',
       'Nº DA PLANILHA', 'STATUS DE PGTO'],
      dtype='object')

In [63]:
excelFile2.dtypes

ENTIDADE                  object
PUBLICAÇÃO                object
Nº de páginas WORD         int64
Nº de páginas estimado     int64
COMPLEXIDADE              object
FORNECEDOR                object
Nº DA PLANILHA             int64
STATUS DE PGTO            object
dtype: object

In [64]:
excelFile2.dtypes

ENTIDADE                  object
PUBLICAÇÃO                object
Nº de páginas WORD         int64
Nº de páginas estimado     int64
COMPLEXIDADE              object
FORNECEDOR                object
Nº DA PLANILHA             int64
STATUS DE PGTO            object
dtype: object

In [65]:
excelFile2

,ENTIDADE,PUBLICAÇÃO,Nº de páginas WORD,Nº de páginas estimado,COMPLEXIDADE,FORNECEDOR,Nº DA PLANILHA,STATUS DE PGTO
0,CNI,Mecanismo de desenvolvimento sustentável e com...,64,90,Alta,Editorar,235806,Empenhado
1,CNI,A difusão das tecnologias da indústria 4.0 em ...,34,48,Baixa,Editorar,235832,Empenhado
2,CNI,Financiamento para Clima,44,48,Baixa,Editorar,235874,Empenhado
3,CNI,Agenda for Germany,30,48,Baixa,Editorar,235876,Empenhado
4,CNI,Estudo sobre o impacto econômico,68,98,Alta,Editorar,235878,Empenhado
5,CNI,Agenda para o México,26,48,Baixa,Editorar,235880,Empenhado
6,CNI,Agenda para o Reino Unido,23,46,Baixa,Editorar,235881,Empenhado
7,CNI,Agenda para a França,22,46,Baixa,Editorar,235883,Empenhado
8,CNI,Agenda para Coreia do Sul,20,46,Baixa,Editorar,235882,Empenhado
9,CNI,Mineração no Brasil,142,198,Alta,Editorar,235798,Empenhado
10,CNI,Proposta de regime para desonerar as importações,75,110,Alta,Editorar,235905,Empenhado
11,CNI,Nova Camex,38,68,Alta,Editorar,235909,Empenhado
12,CNI,Teletrabalho no Brasil e mundo,48,75,Alta,Editorar,235964,Empenhado
13,SESI,Educação Infantil 3 anos,45,70,Alta,Editorar,235979,Empenhado
14,SESI,Educação Infantil 4 e 5 anos,81,114,Alta,Editorar,235980,Empenhado
15,SESI,EJA - Anos Finais,28,48,Baixa,Editorar,235981,Empenhado
16,SESI,EJA - Ensino Médio,30,48,Baixa,Editorar,235984,Empenhado
17,SESI,Ensino Fundamental - Anos Finais,424,460,Alta,Editorar,235985,Empenhado
18,SESI,Ensino Fundamental - Anos Iniciais,373,420,Alta,Editorar,235986,Empenhado
19,SESI,EJA - Anos Iniciais,30,48,Baixa,Editorar,235983,Empenhado
20,CNI,Agenda for Japan,29,48,Baixa,Editorar,236021,Empenhado
21,SESI,Fortalecimento da defesa comercial,24,48,Baixa,Editorar,236025,Empenhado

In [66]:
excelFile2.describe()

       Nº de páginas WORD  Nº de páginas estimado  Nº DA PLANILHA
count           22.000000               22.000000       22.000000
mean            77.181818              103.318182   235922.363636
std            107.962796              114.931610       68.385146
min             20.000000               46.000000   235798.000000
25%             28.250000               48.000000   235878.500000
50%             36.000000               48.000000   235907.000000
75%             67.000000               96.000000   235982.500000
max            424.000000              460.000000   236025.000000

In [67]:
# Verificar se tem alguma inconsistencia na planilha Excel - Quantidade de páginas por exemplo
excelFile2.sort_values('Nº de páginas WORD')

,ENTIDADE,PUBLICAÇÃO,Nº de páginas WORD,Nº de páginas estimado,COMPLEXIDADE,FORNECEDOR,Nº DA PLANILHA,STATUS DE PGTO
8,CNI,Agenda para Coreia do Sul,20,46,Baixa,Editorar,235882,Empenhado
7,CNI,Agenda para a França,22,46,Baixa,Editorar,235883,Empenhado
6,CNI,Agenda para o Reino Unido,23,46,Baixa,Editorar,235881,Empenhado
21,SESI,Fortalecimento da defesa comercial,24,48,Baixa,Editorar,236025,Empenhado
5,CNI,Agenda para o México,26,48,Baixa,Editorar,235880,Empenhado
15,SESI,EJA - Anos Finais,28,48,Baixa,Editorar,235981,Empenhado
20,CNI,Agenda for Japan,29,48,Baixa,Editorar,236021,Empenhado
3,CNI,Agenda for Germany,30,48,Baixa,Editorar,235876,Empenhado
19,SESI,EJA - Anos Iniciais,30,48,Baixa,Editorar,235983,Empenhado
16,SESI,EJA - Ensino Médio,30,48,Baixa,Editorar,235984,Empenhado
1,CNI,A difusão das tecnologias da indústria 4.0 em ...,34,48,Baixa,Editorar,235832,Empenhado
11,CNI,Nova Camex,38,68,Alta,Editorar,235909,Empenhado
2,CNI,Financiamento para Clima,44,48,Baixa,Editorar,235874,Empenhado
13,SESI,Educação Infantil 3 anos,45,70,Alta,Editorar,235979,Empenhado
12,CNI,Teletrabalho no Brasil e mundo,48,75,Alta,Editorar,235964,Empenhado
0,CNI,Mecanismo de desenvolvimento sustentável e com...,64,90,Alta,Editorar,235806,Empenhado
4,CNI,Estudo sobre o impacto econômico,68,98,Alta,Editorar,235878,Empenhado
10,CNI,Proposta de regime para desonerar as importações,75,110,Alta,Editorar,235905,Empenhado
14,SESI,Educação Infantil 4 e 5 anos,81,114,Alta,Editorar,235980,Empenhado
9,CNI,Mineração no Brasil,142,198,Alta,Editorar,235798,Empenhado
18,SESI,Ensino Fundamental - Anos Iniciais,373,420,Alta,Editorar,235986,Empenhado
17,SESI,Ensino Fundamental - Anos Finais,424,460,Alta,Editorar,235985,Empenhado

In [68]:
# verifiacando valores nulos
excelFile2.isnull().sum()

ENTIDADE                  0
PUBLICAÇÃO                0
Nº de páginas WORD        0
Nº de páginas estimado    0
COMPLEXIDADE              0
FORNECEDOR                0
Nº DA PLANILHA            0
STATUS DE PGTO            0
dtype: int64

In [69]:
# retirar registro nulos
excelFile2=excelFile2.dropna()

In [70]:
# verifiacando valores nulos
excelFile2.isnull().sum()

ENTIDADE                  0
PUBLICAÇÃO                0
Nº de páginas WORD        0
Nº de páginas estimado    0
COMPLEXIDADE              0
FORNECEDOR                0
Nº DA PLANILHA            0
STATUS DE PGTO            0
dtype: int64

In [71]:
excelFile2.dtypes

ENTIDADE                  object
PUBLICAÇÃO                object
Nº de páginas WORD         int64
Nº de páginas estimado     int64
COMPLEXIDADE              object
FORNECEDOR                object
Nº DA PLANILHA             int64
STATUS DE PGTO            object
dtype: object

In [72]:
import numpy as np
excelFile2["Nº DA PLANILHA"] = (pd.to_numeric(excelFile2["Nº DA PLANILHA"], errors='coerce').fillna(0).astype(np.int64))#,downcast='integer'))
#excelFile2["Nº DA PLANILHA"] = excelFile2["Nº DA PLANILHA"].astype('int64',errors='ignore')

In [73]:
excelFile2.dtypes

ENTIDADE                  object
PUBLICAÇÃO                object
Nº de páginas WORD         int64
Nº de páginas estimado     int64
COMPLEXIDADE              object
FORNECEDOR                object
Nº DA PLANILHA             int64
STATUS DE PGTO            object
dtype: object

In [74]:
df.dtypes

Nº DA PLANILHA             int64
Qtd_PG_word               object
Qtd_carac                  int64
Qtd_tabela                 int64
Qtd_image                  int64
Qtd_estilos                int64
Data              datetime64[ns]
dtype: object

In [75]:
excelFile2

,ENTIDADE,PUBLICAÇÃO,Nº de páginas WORD,Nº de páginas estimado,COMPLEXIDADE,FORNECEDOR,Nº DA PLANILHA,STATUS DE PGTO
0,CNI,Mecanismo de desenvolvimento sustentável e com...,64,90,Alta,Editorar,235806,Empenhado
1,CNI,A difusão das tecnologias da indústria 4.0 em ...,34,48,Baixa,Editorar,235832,Empenhado
2,CNI,Financiamento para Clima,44,48,Baixa,Editorar,235874,Empenhado
3,CNI,Agenda for Germany,30,48,Baixa,Editorar,235876,Empenhado
4,CNI,Estudo sobre o impacto econômico,68,98,Alta,Editorar,235878,Empenhado
5,CNI,Agenda para o México,26,48,Baixa,Editorar,235880,Empenhado
6,CNI,Agenda para o Reino Unido,23,46,Baixa,Editorar,235881,Empenhado
7,CNI,Agenda para a França,22,46,Baixa,Editorar,235883,Empenhado
8,CNI,Agenda para Coreia do Sul,20,46,Baixa,Editorar,235882,Empenhado
9,CNI,Mineração no Brasil,142,198,Alta,Editorar,235798,Empenhado
10,CNI,Proposta de regime para desonerar as importações,75,110,Alta,Editorar,235905,Empenhado
11,CNI,Nova Camex,38,68,Alta,Editorar,235909,Empenhado
12,CNI,Teletrabalho no Brasil e mundo,48,75,Alta,Editorar,235964,Empenhado
13,SESI,Educação Infantil 3 anos,45,70,Alta,Editorar,235979,Empenhado
14,SESI,Educação Infantil 4 e 5 anos,81,114,Alta,Editorar,235980,Empenhado
15,SESI,EJA - Anos Finais,28,48,Baixa,Editorar,235981,Empenhado
16,SESI,EJA - Ensino Médio,30,48,Baixa,Editorar,235984,Empenhado
17,SESI,Ensino Fundamental - Anos Finais,424,460,Alta,Editorar,235985,Empenhado
18,SESI,Ensino Fundamental - Anos Iniciais,373,420,Alta,Editorar,235986,Empenhado
19,SESI,EJA - Anos Iniciais,30,48,Baixa,Editorar,235983,Empenhado
20,CNI,Agenda for Japan,29,48,Baixa,Editorar,236021,Empenhado
21,SESI,Fortalecimento da defesa comercial,24,48,Baixa,Editorar,236025,Empenhado

In [76]:
# QUANTIDAD DE LINHAS DO ARQUIVO EXCEL PODE DIFERENCIAL DA QUANTIDADE DE LINHAS DO DF (LEITURA DOS ARQUIVOS WORD) 
# PORQUE ALGUNS ARQUIVOS DO WORD NÃO SÃO COM EXTENSÃO .DOCX , OU SEJA O PROGRAMA NÃO TRATA ARQUIVOS .DOC

In [77]:
df

,Nº DA PLANILHA,Qtd_PG_word,Qtd_carac,Qtd_tabela,Qtd_image,Qtd_estilos,Data
0,235880,26,17783,3,2,23,2020-08-26
1,235980,11,163469,12,65,15,2020-09-14
2,235985,424,660609,107,75,27,2020-09-16
3,235983,30,66895,128,77,43,2020-11-09
4,235905,75,97635,147,96,54,2020-08-31
5,235909,38,75538,152,100,21,2020-09-02
6,235876,30,23238,154,109,29,2020-08-21
7,235798,142,247205,175,132,26,2020-08-20
8,235986,374,586948,277,140,21,2020-09-16
9,235874,44,69155,296,148,27,2020-11-09
10,235984,30,78414,315,150,42,2020-11-09
11,235806,64,82304,317,157,25,2020-11-09
12,235882,20,12344,319,159,25,2020-08-26
13,235881,23,14560,321,161,28,2020-08-26
14,235964,48,72824,323,163,16,2020-09-04
15,235878,67,87223,336,175,127,2020-08-17
16,235981,28,65594,359,177,42,2020-11-09
17,235883,22,14344,361,179,29,2020-08-26
18,236021,29,22781,363,181,20,2020-09-19
19,235979,45,72613,370,228,15,2020-09-14
20,235832,34,70983,372,232,16,2020-08-07
21,236025,24,33141,377,237,19,2020-09-16

In [78]:
# unir arquivo do NGE com o método de leitura dos arquivos Word
#
# Atenção >>>>>>>> alguns arquivos não passaram pelo método de leitura dos arquivos word e irão gerar valores NAN
#
df_final = pd.merge(excelFile2, df, on=['Nº DA PLANILHA'], how='left')

In [79]:
# colocando ordem das colunas adequada
excelFile2.columns
#colunas_final = ['Nº DA PLANILHA','ENTIDADE',  'FORNECEDOR','COMPLEXIDADE', 'STATUS DE PGTO',  'Nº de páginas WORD','Nº de páginas estimado', 'Qtd_carac','Qtd_tabela', 'Qtd_image','Nº de páginas finais' ]
colunas_final = ['Nº DA PLANILHA','ENTIDADE',  'FORNECEDOR','COMPLEXIDADE', 'STATUS DE PGTO',  'Nº de páginas WORD','Nº de páginas estimado', "Qtd_PG_word",'Qtd_carac','Qtd_tabela', 'Qtd_image',"Qtd_estilos"]
df_final = df_final[colunas_final]

In [80]:
# -----> verificar valores NAN 
df_final.isnull().sum()
# OS REGISTROS COM NAN NESSE CASO FORAM OS ARQUIVOS WORD QUE NÃO FOI ENCONTRADO.

Nº DA PLANILHA            0
ENTIDADE                  0
FORNECEDOR                0
COMPLEXIDADE              0
STATUS DE PGTO            0
Nº de páginas WORD        0
Nº de páginas estimado    0
Qtd_PG_word               0
Qtd_carac                 0
Qtd_tabela                0
Qtd_image                 0
Qtd_estilos               0
dtype: int64

In [81]:
# retirar registro nulos
df_final=df_final.dropna()
# APAGOU AS LINHAS COM NAN

In [82]:
# -----> verificar valores NAN 
df_final.isnull().sum()

Nº DA PLANILHA            0
ENTIDADE                  0
FORNECEDOR                0
COMPLEXIDADE              0
STATUS DE PGTO            0
Nº de páginas WORD        0
Nº de páginas estimado    0
Qtd_PG_word               0
Qtd_carac                 0
Qtd_tabela                0
Qtd_image                 0
Qtd_estilos               0
dtype: int64

In [83]:
df_final

,Nº DA PLANILHA,ENTIDADE,FORNECEDOR,COMPLEXIDADE,STATUS DE PGTO,Nº de páginas WORD,Nº de páginas estimado,Qtd_PG_word,Qtd_carac,Qtd_tabela,Qtd_image,Qtd_estilos
0,235806,CNI,Editorar,Alta,Empenhado,64,90,64,82304,317,157,25
1,235832,CNI,Editorar,Baixa,Empenhado,34,48,34,70983,372,232,16
2,235874,CNI,Editorar,Baixa,Empenhado,44,48,44,69155,296,148,27
3,235876,CNI,Editorar,Baixa,Empenhado,30,48,30,23238,154,109,29
4,235878,CNI,Editorar,Alta,Empenhado,68,98,67,87223,336,175,127
5,235880,CNI,Editorar,Baixa,Empenhado,26,48,26,17783,3,2,23
6,235881,CNI,Editorar,Baixa,Empenhado,23,46,23,14560,321,161,28
7,235883,CNI,Editorar,Baixa,Empenhado,22,46,22,14344,361,179,29
8,235882,CNI,Editorar,Baixa,Empenhado,20,46,20,12344,319,159,25
9,235798,CNI,Editorar,Alta,Empenhado,142,198,142,247205,175,132,26
10,235905,CNI,Editorar,Alta,Empenhado,75,110,75,97635,147,96,54
11,235909,CNI,Editorar,Alta,Empenhado,38,68,38,75538,152,100,21
12,235964,CNI,Editorar,Alta,Empenhado,48,75,48,72824,323,163,16
13,235979,SESI,Editorar,Alta,Empenhado,45,70,45,72613,370,228,15
14,235980,SESI,Editorar,Alta,Empenhado,81,114,11,163469,12,65,15
15,235981,SESI,Editorar,Baixa,Empenhado,28,48,28,65594,359,177,42
16,235984,SESI,Editorar,Baixa,Empenhado,30,48,30,78414,315,150,42
17,235985,SESI,Editorar,Alta,Empenhado,424,460,424,660609,107,75,27
18,235986,SESI,Editorar,Alta,Empenhado,373,420,374,586948,277,140,21
19,235983,SESI,Editorar,Baixa,Empenhado,30,48,30,66895,128,77,43
20,236021,CNI,Editorar,Baixa,Empenhado,29,48,29,22781,363,181,20
21,236025,SESI,Editorar,Baixa,Empenhado,24,48,24,33141,377,237,19

In [84]:
# reindexar o index devido ter deletado algumas linhas
df_final.reset_index(drop=True, inplace=True)

In [85]:
df_final.dtypes

Nº DA PLANILHA             int64
ENTIDADE                  object
FORNECEDOR                object
COMPLEXIDADE              object
STATUS DE PGTO            object
Nº de páginas WORD         int64
Nº de páginas estimado     int64
Qtd_PG_word               object
Qtd_carac                  int64
Qtd_tabela                 int64
Qtd_image                  int64
Qtd_estilos                int64
dtype: object

In [86]:
df_final.head()

,Nº DA PLANILHA,ENTIDADE,FORNECEDOR,COMPLEXIDADE,STATUS DE PGTO,Nº de páginas WORD,Nº de páginas estimado,Qtd_PG_word,Qtd_carac,Qtd_tabela,Qtd_image,Qtd_estilos
0,235806,CNI,Editorar,Alta,Empenhado,64,90,64,82304,317,157,25
1,235832,CNI,Editorar,Baixa,Empenhado,34,48,34,70983,372,232,16
2,235874,CNI,Editorar,Baixa,Empenhado,44,48,44,69155,296,148,27
3,235876,CNI,Editorar,Baixa,Empenhado,30,48,30,23238,154,109,29
4,235878,CNI,Editorar,Alta,Empenhado,68,98,67,87223,336,175,127

In [87]:
# alterar campos typo string para categóricos 
df_final['ENTIDADE'] = df_final['ENTIDADE'].astype('category')
df_final['COMPLEXIDADE'] = df_final['COMPLEXIDADE'].astype('category')
df_final['FORNECEDOR'] = df_final['FORNECEDOR'].astype('category')
df_final['STATUS DE PGTO'] = df_final['STATUS DE PGTO'].astype('category')

In [88]:
# alterar campos typo categóricos para numérico
# aplicando .cat.codes em cada uma dessas colunas
df_final['ENTIDADE'] = df_final['ENTIDADE'].cat.codes
df_final['COMPLEXIDADE'] = df_final['COMPLEXIDADE'].cat.codes
df_final['FORNECEDOR'] = df_final['FORNECEDOR'].cat.codes
df_final['STATUS DE PGTO'] = df_final['STATUS DE PGTO'].cat.codes

In [89]:
df_final['Nº de páginas WORD'] = df_final['Nº de páginas WORD'].astype('int')

In [90]:
# Verificar se tem alguma inconsistencia na planilha Excel - Quantidade de páginas por exemplo
df_final.sort_values('Nº de páginas WORD')

# eliminar linhas com menos de 10 páginas
filtro  = df_final['Nº de páginas WORD'] > 10
df_final = df_final[filtro]

In [91]:
df_final.dtypes

Nº DA PLANILHA             int64
ENTIDADE                    int8
FORNECEDOR                  int8
COMPLEXIDADE                int8
STATUS DE PGTO              int8
Nº de páginas WORD         int64
Nº de páginas estimado     int64
Qtd_PG_word               object
Qtd_carac                  int64
Qtd_tabela                 int64
Qtd_image                  int64
Qtd_estilos                int64
dtype: object

In [92]:
df_final.head()

,Nº DA PLANILHA,ENTIDADE,FORNECEDOR,COMPLEXIDADE,STATUS DE PGTO,Nº de páginas WORD,Nº de páginas estimado,Qtd_PG_word,Qtd_carac,Qtd_tabela,Qtd_image,Qtd_estilos
0,235806,0,0,0,0,64,90,64,82304,317,157,25
1,235832,0,0,1,0,34,48,34,70983,372,232,16
2,235874,0,0,1,0,44,48,44,69155,296,148,27
3,235876,0,0,1,0,30,48,30,23238,154,109,29
4,235878,0,0,0,0,68,98,67,87223,336,175,127

In [93]:
df_final.columns

Index(['Nº DA PLANILHA', 'ENTIDADE', 'FORNECEDOR', 'COMPLEXIDADE',
       'STATUS DE PGTO', 'Nº de páginas WORD', 'Nº de páginas estimado',
       'Qtd_PG_word', 'Qtd_carac', 'Qtd_tabela', 'Qtd_image', 'Qtd_estilos'],
      dtype='object')

In [94]:
# trocar type float por int
df_final["Qtd_PG_word"] = df_final["Qtd_PG_word"].astype('int')
df_final['Qtd_carac'] = df_final['Qtd_carac'].astype('int')
df_final['Qtd_tabela'] = df_final['Qtd_tabela'].astype('int')
df_final['Qtd_image'] = df_final['Qtd_image'].astype('int')

In [95]:
df_final.columns

Index(['Nº DA PLANILHA', 'ENTIDADE', 'FORNECEDOR', 'COMPLEXIDADE',
       'STATUS DE PGTO', 'Nº de páginas WORD', 'Nº de páginas estimado',
       'Qtd_PG_word', 'Qtd_carac', 'Qtd_tabela', 'Qtd_image', 'Qtd_estilos'],
      dtype='object')

In [96]:
df_final.dtypes

Nº DA PLANILHA            int64
ENTIDADE                   int8
FORNECEDOR                 int8
COMPLEXIDADE               int8
STATUS DE PGTO             int8
Nº de páginas WORD        int64
Nº de páginas estimado    int64
Qtd_PG_word               int64
Qtd_carac                 int64
Qtd_tabela                int64
Qtd_image                 int64
Qtd_estilos               int64
dtype: object

In [97]:
#renomear colunas

#df_final.rename(columns={'Nº DA PLANILHA': 'id','ENTIDADE':"entidade",'FORNECEDOR':"fornecedor", 'COMPLEXIDADE':"complexidade",
#                         'STATUS DE PGTO':"stat_pagto",'Nº de páginas WORD':"qtd_pag_word", 
#                         'Nº de páginas estimado':"qtd_pag_estimado", 'Qtd_carac':"qtd_carc",
#       'Qtd_tabela':"qtd_tabela", 'Qtd_image': "qtd_image", 'Nº de páginas finais':"pag_final"} , inplace = True)

df_final.rename(columns={'Nº DA PLANILHA': 'id','ENTIDADE':"entidade",'FORNECEDOR':"fornecedor", 'COMPLEXIDADE':"complexidade",
                         'STATUS DE PGTO':"stat_pagto",'Nº de páginas WORD':"qtd_pag_word", 
                         'Nº de páginas estimado':"qtd_pag_estimado", "Qtd_PG_word":"qtd_pg_word",'Qtd_carac':"qtd_carc",
       'Qtd_tabela':"qtd_tabela", 'Qtd_image': "qtd_image","Qtd_estilos":"qtd_estilos"} , inplace = True)

In [98]:
df_final['tamanho_livro'] = 'NaN'
for index, row in df_final.iterrows():
    #print(row["pag_final"])
    if row["qtd_pg_word"]>119:
        df_final.loc[index,'tamanho_livro'] =  2
    elif row["qtd_pg_word"]>59 & row["qtd_pg_word"]<120:
        df_final.loc[index,'tamanho_livro'] =  1
    else:  
        df_final.loc[index,'tamanho_livro'] =  0

In [101]:
df_final.columns

Index(['id', 'entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word', 'qtd_pag_estimado', 'qtd_pg_word', 'qtd_carc',
       'qtd_tabela', 'qtd_image', 'qtd_estilos', 'tamanho_livro'],
      dtype='object')

In [99]:
# gerar arquivo csv para arquivo tratado

df_final.to_csv("nge_dados_input_semNF.csv",index=False )

#data = pd.read_csv("nge_dados_input.csv")
#df_final.to_csv(index=False)
#df_final.to_csv("nge_dados_input.csv", data = imprimir_ano)

In [100]:
df_final['tamanho_livro'] ==  1

0      True
1     False
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11     True
12    False
13     True
14    False
15     True
16     True
17    False
18    False
19     True
20     True
21    False
Name: tamanho_livro, dtype: bool

In [ ]:
#colunas_X= ['complexidade', 'qtd_pag_word', 'qtd_carc','qtd_tabela','qtd_image',"qtd_estilos",'qtd_carc_normal']